### Filtering in Pandas

In [1]:
import pandas as pd
import numpy as np

In [9]:
# load the dataset
athlete = pd.read_csv('bios.csv')

In [12]:
athlete.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [14]:
athlete.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   name          145500 non-null  object
 2   born_date     143693 non-null  object
 3   born_city     110908 non-null  object
 4   born_region   110908 non-null  object
 5   born_country  110908 non-null  object
 6   NOC           145499 non-null  object
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   object
dtypes: float64(2), int64(1), object(7)
memory usage: 11.1+ MB

In [ ]:
# athlete.loc[athlete['height_cm'] > 200]
athlete[athlete['height_cm'] > 200] # shortform

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
1080,1087,Bozhil Lozanov,1934-08-16,NaN,NaN,NaN,Bulgaria,208.0,133.0,NaN
1673,1680,Alexis Rubalcaba,1972-08-09,Pedro Betancourt,Matanzas,CUB,Cuba,204.0,95.0,NaN
2647,2659,Milan Šrejber,1963-12-30,Praha (Prague),Hlavní město Praha,CZE,Czechoslovakia,203.0,98.0,NaN
2827,2839,Nik'oloz Deriugini,1959-04-30,Kutaisi,Imereti,GEO,Soviet Union,206.0,105.0,NaN
2832,2844,Elşad Qadaşev,1968-05-01,Bakı,Bakı,AZE,Unified Team,205.0,110.0,NaN
...,...,...,...,...,...,...,...,...,...,...
143784,147440,Daniel Miklasevich,1997-07-17,NaN,NaN,NaN,United States,203.0,NaN,NaN
143833,147489,Garrett Muagututia,1988-02-26,NaN,NaN,NaN,United States,205.0,NaN,NaN
143834,147490,Kyle Ensing,1997-03-06,NaN,NaN,NaN,United States,201.0,NaN,NaN
143835,147491,Mitch Stahl,1994-08-31,NaN,NaN,NaN,United States,203.0,NaN,NaN
143919,147577,Emerson Rodríguez,1993-02-02,Caracas,Distrito Capital,VEN,Venezuela,204.0,NaN,NaN

In [ ]:
# athlete.loc[athlete['height_cm'] > 200, ['name', 'height_cm']] 

# use shortform to select columns

athlete[athlete['height_cm'] > 200] [['name', 'height_cm', 'born_country']]

                      name  height_cm born_country
1080        Bozhil Lozanov      208.0          NaN
1673      Alexis Rubalcaba      204.0          CUB
2647         Milan Šrejber      203.0          CZE
2827    Nik'oloz Deriugini      206.0          GEO
2832         Elşad Qadaşev      205.0          AZE
...                    ...        ...          ...
143784  Daniel Miklasevich      203.0          NaN
143833  Garrett Muagututia      205.0          NaN
143834         Kyle Ensing      201.0          NaN
143835         Mitch Stahl      203.0          NaN
143919   Emerson Rodríguez      204.0          VEN

[1219 rows x 3 columns]

In [24]:
# combining conditions
athlete[(athlete['height_cm'] > 210) & (athlete['born_country'] =='USA')]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
5681,5704,Walt Bellamy,1937-07-24,New Bern,North Carolina,USA,United States,211.0,98.0,2013-11-02
5781,5804,Tommy Burleson,1952-02-24,Crossnore,North Carolina,USA,United States,223.0,102.0,NaN
5894,5919,Mel Counts,1941-10-16,Coos Bay,Oregon,USA,United States,213.0,102.0,NaN
6106,6133,Marc Freiberger,1928-11-27,Amarillo,Texas,USA,United States,211.0,98.0,2005-06-29
6281,6309,Darrall Imhoff,1938-10-11,San Gabriel,California,USA,United States,211.0,98.0,2017-06-30
6379,6410,Joe Kleine,1962-01-04,Colorado Springs,Colorado,USA,United States,211.0,122.0,NaN
6393,6424,Jon Koncak,1963-05-17,Cedar Rapids,Iowa,USA,United States,213.0,113.0,NaN
6442,6473,Christian Laettner,1969-08-17,Angola,New York,USA,United States,211.0,107.0,NaN
6615,6648,Tom McMillen,1952-05-26,Mansfield,Pennsylvania,USA,United States,212.0,95.0,NaN
6722,6755,Shaquille O'Neal,1972-03-06,Newark,New Jersey,USA,United States,216.0,137.0,NaN
6937,6972,David Robinson,1965-08-06,Key West,Florida,USA,United States,216.0,107.0,NaN
7012,7048,Daniel Santiago,1976-06-24,Tarpon Springs,Florida,USA,Puerto Rico,213.0,111.0,NaN
112319,113575,Chris Kaman,1982-04-28,Wyoming,Michigan,USA,Germany,213.0,122.0,NaN
112366,113622,Dwight Howard,1985-12-08,Atlanta,Georgia,USA,United States,211.0,120.0,NaN
118573,120309,Al-Farouq Aminu,1990-09-21,Atlanta,Georgia,USA,Nigeria,211.0,98.0,NaN
123850,126093,Tyson Chandler,1982-10-02,Hanford,California,USA,United States,216.0,107.0,NaN
132188,135037,Domantas Sabonis,1996-05-03,Portland,Oregon,USA,Lithuania,211.0,109.0,NaN
133332,136271,DeAndre Jordan,1988-07-21,Houston,Texas,USA,United States,211.0,120.0,NaN
142044,145640,Jahlil Okafor,1995-12-15,Fort Smith,Arkansas,USA,Nigeria,211.0,NaN,NaN
142930,146560,Mike Tobey,1994-10-10,Monroe,New York,USA,Slovenia,213.0,NaN,NaN
143712,147367,JaVale McGee,1988-01-19,Flint,Michigan,USA,United States,213.0,NaN,NaN

In [ ]:
# string operations
# athlete[athlete['name'].str.contains("Smith")]
# athlete[athlete['name'].str.contains("Smith", na=False)] # to avoid NaN error
athlete[athlete['name'].str.contains("smith", case=False)] # case insensitive

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
46,47,Gladys Eastlake-Smith,1883-08-14,Lewisham,England,GBR,Great Britain,NaN,NaN,1941-09-18
68,69,Sam Smith,1971-11-27,Epping,England,GBR,Great Britain,175.0,62.0,NaN
659,662,Roger Smith,1964-01-20,Freeport,City of Freeport,BAH,The Bahamas,185.0,79.0,NaN
1031,1038,Trygve Smith,1880-09-20,Oslo,Oslo,NOR,Norway,NaN,NaN,1948-11-10
1426,1433,Julie Smith,1968-05-10,Glendora,California,USA,United States,162.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
143586,147239,Austen Smith,2001-07-23,NaN,NaN,NaN,United States,170.0,NaN,NaN
143591,147244,Alana Smith,2000-10-20,Mesa,Arizona,USA,United States,NaN,NaN,NaN
143629,147282,Regan Smith,2002-02-09,Lakeville,Minnesota,USA,United States,NaN,NaN,NaN
143816,147472,Kieran Smith,2000-05-20,NaN,NaN,NaN,United States,NaN,NaN,NaN
145421,149144,Nathan Smith,1998-10-19,Tampa,Florida,USA,United States,NaN,NaN,NaN

In [ ]:
#isin 
# athlete[athlete['born_country'].isin(['USA', 'CAN'])] # filter by multiple values
athlete[athlete['born_country'].isin(['USA', 'CAN']) & (athlete['height_cm'] > 200)] # combine with other conditions

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
54,55,Monique Javer,1967-07-22,Burlingame,California,USA,Great Britain,177.0,64.0,NaN
114,115,Greg Rusedski,1973-09-06,Montréal,Québec,CAN,Great Britain,190.0,88.0,NaN
361,362,Wanda Allan-Sadegur,1955-01-24,Victoria,British Columbia,CAN,Canada,165.0,91.0,NaN
363,364,Mary Grant,1949-02-27,Windsor,Ontario,CAN,Canada,169.0,NaN,NaN
364,365,Linda Kazienko,1955-05-29,Grimsby,Ontario,CAN,Canada,175.0,61.0,NaN
...,...,...,...,...,...,...,...,...,...,...
145457,149183,Alix Wilkinson,2000-08-02,Mammoth Lakes,California,USA,United States,NaN,NaN,NaN
145461,149188,Kent Johnson,2002-10-18,Port Moody,British Columbia,CAN,Canada,185.0,75.0,NaN
145462,149189,Morgan Ellis,1992-04-30,Summerside,Prince Edward Island,CAN,Canada,187.0,94.0,NaN
145468,149195,Justin Abdelkader,1987-02-25,Muskegon,Michigan,USA,United States,187.0,97.0,NaN
145494,149221,George Wright,1890-07-21,Toronto,Ontario,CAN,Canada,183.0,NaN,1973-01-28

In [47]:
athlete[athlete['born_country'].isin(['USA', 'CAN']) & (athlete['name'].str.startswith('James'))]
# athlete[athlete['born_country'].str.startswith('KEN')]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
5814,5837,James Carter,1964-03-27,New York,New York,USA,Puerto Rico,183.0,95.0,NaN
8586,8633,James Busceme,1952-02-14,Beaumont,Texas,USA,United States,171.0,60.0,NaN
9248,9301,James Nickel,1930-02-09,Winnipeg,Manitoba,CAN,Canada,NaN,NaN,1990-03-30
11080,11139,James O'Rourke,1915-05-04,Yonkers,New York,USA,United States,NaN,NaN,1983-11-21
11081,11140,"James O'Rourke, Jr.",1942-05-06,Yonkers,New York,USA,United States,180.0,80.0,NaN
...,...,...,...,...,...,...,...,...,...,...
136867,140103,James McGuire,2003-03-03,Queensbury,New York,USA,United States,NaN,NaN,NaN
138105,141497,James Palmer,1994-11-03,North Vancouver,British Columbia,CAN,Canada,NaN,NaN,NaN
138134,141526,James Kirkpatrick,1991-03-29,Victoria,British Columbia,CAN,Canada,NaN,NaN,NaN
143796,147452,James Hall,1983-11-18,Alabaster,Alabama,USA,United States,183.0,91.0,NaN
145350,149073,James Reed,1991-05-23,Bloomington,Indiana,USA,United States,NaN,NaN,NaN

In [ ]:
# query function
athlete.query('born_country == "USA"')

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
54,55,Monique Javer,1967-07-22,Burlingame,California,USA,Great Britain,177.0,64.0,NaN
960,964,Xóchitl Escobedo,1968-09-17,West Covina,California,USA,Mexico,170.0,60.0,NaN
961,965,Angélica Gavaldón,1973-10-03,El Centro,California,USA,Mexico,160.0,54.0,NaN
1231,1238,Bert Schneider,1897-07-01,Cleveland,Ohio,USA,Canada,NaN,NaN,1986-02-20
1345,1352,Laura Berg,1975-01-06,Santa Fe Springs,California,USA,United States,168.0,61.0,NaN
...,...,...,...,...,...,...,...,...,...,...
145445,149168,Kristen Santos,1994-11-02,Fairfield,Connecticut,USA,United States,NaN,NaN,NaN
145446,149169,Corinne Stoddard,2001-08-15,Seattle,Washington,USA,United States,NaN,NaN,NaN
145454,149180,Anna Hoffmann,2000-03-28,Madison,Wisconsin,USA,United States,NaN,NaN,NaN
145457,149183,Alix Wilkinson,2000-08-02,Mammoth Lakes,California,USA,United States,NaN,NaN,NaN
145468,149195,Justin Abdelkader,1987-02-25,Muskegon,Michigan,USA,United States,187.0,97.0,NaN

In [ ]:
# athlete.query('born_country == "USA" & height_cm > 200') # combine with other conditions 

# athlete.query('born_country in ["USA", "CAN"]') # filter by multiple values

athlete.query('born_country in ["USA", "CAN"] & name.str.startswith("James")') # combine with other conditions

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
5197,5216,Anne Donovan,1961-11-01,Ridgewood,New Jersey,USA,United States,203.0,62.0,2018-06-13
5652,5675,Mike Bantom,1951-12-03,Philadelphia,Pennsylvania,USA,United States,203.0,93.0,NaN
5657,5680,Jim Barnes,1941-04-13,Tuckerman,Arkansas,USA,United States,201.0,109.0,2002-09-14
5681,5704,Walt Bellamy,1937-07-24,New Bern,North Carolina,USA,United States,211.0,98.0,2013-11-02
5709,5732,Larry Bird,1956-12-07,French Lick,Indiana,USA,United States,205.0,100.0,NaN
...,...,...,...,...,...,...,...,...,...,...
143706,147361,Bam Adebayo,1997-07-18,Newark,New Jersey,USA,United States,206.0,116.0,NaN
143707,147362,Jerami Grant,1994-03-12,Portland,Oregon,USA,United States,203.0,95.0,NaN
143710,147365,Khris Middleton,1991-08-12,Charleston,South Carolina,USA,United States,201.0,101.0,NaN
143712,147367,JaVale McGee,1988-01-19,Flint,Michigan,USA,United States,213.0,NaN,NaN
143733,147388,Nick Allen,1998-10-08,San Diego,California,USA,United States,203.0,NaN,NaN